language: cpp
compiler:
  - gcc
  - clang
script: 
  - scons --build=debug --with-tools
  - scons --with-tools
branches:
  only:
    - master
    - develop
notifications:
  recipients:
    - info@project-osrm.org
  email:
    on_success: change
    on_failure: always
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential git scons pkg-config libprotoc-dev libprotobuf7 protobuf-compiler libprotobuf-dev libosmpbf-dev libpng-dev libbz2-dev libstxxl-dev libstxxl-doc libstxxl1 libxml2-dev libzip-dev libboost-thread-dev libboost-system-dev libboost-regex-dev libboost-filesystem-dev lua5.1 liblua5.1-0-dev libluabind-dev
