environment:
  matrix:
  - configuration: Debug
  - configuration: Release

# branches to build
branches:
  # whitelist
  only:
    - win-038
#   - develop
#TODO: replace with develop branch when merged

# Operating system (build VM template)
os: Windows Server 2012 R2

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\osrm

platform: x64

install:
  # by default, all script lines are interpreted as batch
  - cd c:\projects\osrm
  - curl -O http://build.project-osrm.org/libs_osrm_%Configuration%.7z
  - 7z x libs_osrm_%Configuration%.7z | find ":"

build_script:
  - cd c:/projects/osrm
  - mkdir build
  - cd build
  - echo Running cmake...
  - call "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat" x86_amd64
  - SET P=c:/projects/osrm
  - set TBB_INSTALL_DIR=%P%/tbb
  - set TBB_ARCH_PLATFORM=intel64/vc12
  - cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=%Configuration% -DBZIP2_INCLUDE_DIR=%P%/libs/include -DBZIP2_LIBRARIES=%P%/libs/lib/libbz2.lib -DCMAKE_INSTALL_PREFIX=%P%/libs -DBOOST_ROOT=%P%/boost_min -DBoost_USE_STATIC_LIBS=ON
  - nmake
  - 7z a %P%/osrm_%Configuration%.zip *.exe *.pdb %P%/libs/bin/*.dll -tzip

test: off

artifacts:
  - path: osrm_Debug.zip
    name: osrm_Debug.zip
  - path: osrm_Release.zip
    name: osrm_Release.zip

#deploy:
#  provider: FTP
#  server: ftp.mample.com
#  username: user
#  password:
#    secure: XMdn4xfPcYlZFYgvbytc8Q==
#  folder: osrm
#  enable_ssl: true|false (disabled by default)
#  artifact: /.*\.zip/
